### PR TITLE
fix: Don't panic on `name_too_long` error

### LINKED ISSUE #246: deno-postgres panics on `name_too_long` error
## Summary

I noticed that deno-postgres panics when PostgreSQL returns `name_too_long` error. I think deno-postgres should handle this error like [node-postgres](https://github.com/brianc/node-postgres) does. (See `Additional information`)

## Steps to reproduce

Run the following code with `deno run` command:

```typescript
import { Client } from "https://deno.land/x/postgres@v0.7.1/mod.ts"

const client = new Client({
  "applicationName": "deno-postgres",
  "database": "deno-postgres",
  "hostname": "127.0.0.1",
  "password": "test",
  "port": 5432,
  "user": "test"
});
await client.connect();

const result = await client.queryArray(`
  SELECT 1 AS "very_very_very_very_very_very_very_very_very_very_very_long_name"
`);
```

Error message in the console:

```shell
NOTICE: identifier "very_very_very_very_very_very_very_very_very_very_very_long_name" will be truncated to "very_very_very_very_very_very_very_very_very_very_very_long_nam"
error: Uncaught (in promise) Error: Unexpected frame: T
                    throw new Error(`Unexpected frame: ${msg.type}`);
```

## Environment

* deno-postgres@v0.7.1
* deno@v1.7.2

## Additional information

When running the same query with node-postgres, it works as follows:

```javascript
const { Client } = require('pg');

const client = new Client({
  database: "deno-postgres",
  host: "127.0.0.1",
  password: "test",
  port: 5432,
  user: "test"
});
client.connect();

client.query(`SELECT 1 AS "very_very_very_very_very_very_very_very_very_very_very_long_name"`, (err, res) => {
  if (err) {
    console.error(err);
  } else {
    console.log(res.rows);
  }
  client.end();
});
```

**Output:**

```shell
[
  {
    very_very_very_very_very_very_very_very_very_very_very_long_nam: 1
  }
]
```

## Ref

https://www.postgresql.org/docs/13/errcodes-appendix.html

### PR DESCRIPTION
**Pull request by uki00a**
This PR fixes #246.

### CODE REVIEW

File: tests/queries.ts [hunk 1]
```diff
@@ -184,3 +184,13 @@ testClient(async function transactionWithConcurrentQueries() {
     assertEquals(r.rows[0][0], i);
   });
 });
+
+testClient(async function handleNameTooLongError() {
+  const result = await CLIENT.queryObject(`
+    SELECT id AS "very_very_very_very_very_very_very_very_very_very_very_long_name" FROM ids ORDER BY id
```
Comment (Soremwar) [inline tests/queries.ts:190]: Please don't use the ids table for the test (I'm trying to get rid of the fixtures used for the tests and use temporally generated ones instead). Do something like `SELECT 1 AS very_very_very_very_very_very_very_very_very_very_very_long_name`

**Review by Soremwar — CHANGES_REQUESTED** [review]

**Review by Soremwar — APPROVED** [review]

**Comment by Soremwar** [comment]
LGTM. Thank you @uki00a
